title: 성장하는 개발자의 블로그
subtitle: keep going since 2021. 12
description: >-
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is
  optimized for speed and readability.
url: ''
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url: /shop
  - text: Contact
    url: /contact
author_logo: profile.png
author: MinHee Lee
author_bio: 'Hi, my name is MinHee Lee.'
author_email: lmh5284@gmail.com
author_location: Korea
author_website_url: null
typewrite-text: Welcome My World
hero_cover_img: sample_cover.jpg
author_work_experiences:
  - company_name: Google
    company_logo: google.png
    company_url: 'https://google.com'
    designation: Software Engineer
    description: Worked on various Google Products
    visibility: false
  - company_name: Microsoft
    company_logo: microsoft.png
    company_url: 'https://microsoft.com'
    designation: Azure Developer
    description: Worked on various Azure Cloud Products
    visibility: false
author_education_details:
  - college_logo: mit.png
    college_name: DaeJeon University
    college_url: 'https://www.dju.ac.kr/dju/main.do'
    college_degree: CS Engineer
    description: null
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: false
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: false
twitter_username: johndoe
github_username: not-mini
facebook_username: null
linkedin_username: null
behance_username: null
instagram_username: null
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null
hyvor_talk_website_id: 476
wakatime_username: sujaykundu777
mailchimp_form_url: >-
  https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0
formspree_email: johndoe@gmail.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: true
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
